---
- hosts: localhost
  gather_facts: False

  vars:
    region: us-east-1
    instance_type: t2.micro
    ami: <ami-id>
    keypair: <key-pair name>
    
  tasks:
    - name: Create new EC2 instance
      ec2:
        key_name: "{{ keypair }}"
        aws_access_key: "{{ aws_acc_key }}" #declare variables in input file and provide by extravars args
        aws_secret_key: "{{ aws_secret_key }}"
        group: Ansible-sg1 #Ansible security group name
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: True
        region: "{{ region }}"
        count: 1
        count_tag: 
          Name: "Created-by-ansible"
        instance_tags:
          Name: "Ansible-created"
        vpc_subnet_id: "<subnetid from aws>"
        assign_public_ip: yes
      register: ec2
    - name: Print ec2 module output
      debug: var=ec2

    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - set_fact: ip_list= "[]" #dynamic variable

    - name: Constructing IP list
      set_fact: ip_list= "[{{ item.private_ip }}]"
      with_items: "{{ ec2.instances }}"

    - name: Print IP list
      debug: msg = "{{ ip_list }}" 
