---
- hosts: localhost
  vars:
    web_dependencies:
         - python
         - python-setuptools
         - python-dev
         - build-essential
         - python-pip
         - python-mysqldb
    sql_dependencies:
         - python
         - python-mysqldb
  tasks:
  - name: install dependencies
    debug: msg='{{ item }}'
    with_items: '{{ sql_dependencies | union(web_dependencies) }}'
